# Generated by Django 3.1.1 on 2020-10-01 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtor',
            old_name='photo',
            new_name='image',
        ),
    ]
