# Generated by Django 3.1.1 on 2020-10-02 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0002_auto_20201001_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtor',
            old_name='image',
            new_name='photo',
        ),
    ]
